# db-controller.yml
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
  name: mongo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo:3.2.4
        name: mongo
        command:
            - mongod
            - "--logappend"
            - "--logpath"
            - /var/log/mongodb/mongod.log
            - "--bind_ip"
            - 0.0.0.0
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: mypd
      volumes:
        - name: mypd
          cinder:
            volumeID: ce47a25a-87f8-4895-b485-a6c86bbf906f
            fsType: ext4
             
