apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2016-03-29T12:31:52Z
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: KubeDNS
  name: kube-dns
  namespace: kube-system
  resourceVersion: "122336"
  selfLink: /api/v1/namespaces/kube-system/services/kube-dns
  uid: 376407f4-f5aa-11e5-bf5e-fa163ec4c512
spec:
  clusterIP: 10.1.69.10
  ports:
  - name: dns
    nodePort: 30002
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    nodePort: 30003
    port: 53
    protocol: TCP
    targetPort: 53
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
