# db-controller.yml
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
  name: mongo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: mypd
      nodeSelector:
        mongodbHost: "true"
      volumes:
        - name: mypd
          persistentVolumeClaim:
             claimName: myclaim-1
