apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 32004
  selector:
    name: mongo
  type: LoadBalancer
